In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Python environment is ready")

Python environment is ready

In [2]:
from pathlib import Path

data_dir = Path("../data/raw/dataset1")

print(data_dir)

../data/raw/dataset1

In [3]:
files = list(data_dir.glob("*.csv"))

for file in files:
    print(file)

../data/raw/dataset1/rare_user.csv
../data/raw/dataset1/heavy_user.csv
../data/raw/dataset1/daily_user.csv
../data/raw/dataset1/moderate_user.csv

In [4]:
daily_df = pd.read_csv(data_dir / "daily_user.csv")
heavy_df = pd.read_csv(data_dir / "heavy_user.csv")
moderate_df = pd.read_csv(data_dir / "moderate_user.csv")
rare_df = pd.read_csv(data_dir / "rare_user.csv")

In [5]:
print("Daily:", daily_df.shape)
print("Heavy:", heavy_df.shape)
print("Moderate:", moderate_df.shape)
print("Rare:", rare_df.shape)

Daily: (43800, 12)
Heavy: (43800, 12)
Moderate: (43800, 12)
Rare: (43800, 12)

In [6]:
print("Daily columns:")
print(daily_df.columns.tolist())

print("\nHeavy columns:")
print(heavy_df.columns.tolist())

print("\nModerate columns:")
print(moderate_df.columns.tolist())

print("\nRare columns:")
print(rare_df.columns.tolist())

Daily columns:
['Unnamed: 0', 'SOC', 'SOH', 'Charging_Cycles', 'Battery_Temp', 'Motor_RPM', 'Motor_Torque', 'Motor_Temp', 'Brake_Pad_Wear', 'Charging_Voltage', 'Tire_Pressure', 'DTC']

Heavy columns:
['Unnamed: 0', 'SOC', 'SOH', 'Charging_Cycles', 'Battery_Temp', 'Motor_RPM', 'Motor_Torque', 'Motor_Temp', 'Brake_Pad_Wear', 'Charging_Voltage', 'Tire_Pressure', 'DTC']

Moderate columns:
['Unnamed: 0', 'SOC', 'SOH', 'Charging_Cycles', 'Battery_Temp', 'Motor_RPM', 'Motor_Torque', 'Motor_Temp', 'Brake_Pad_Wear', 'Charging_Voltage', 'Tire_Pressure', 'DTC']

Rare columns:
['Unnamed: 0', 'SOC', 'SOH', 'Charging_Cycles', 'Battery_Temp', 'Motor_RPM', 'Motor_Torque', 'Motor_Temp', 'Brake_Pad_Wear', 'Charging_Voltage', 'Tire_Pressure', 'DTC']

In [7]:
schemas_match = (
    list(daily_df.columns) == list(heavy_df.columns) ==
    list(moderate_df.columns) == list(rare_df.columns)
)

print("All schemas identical:", schemas_match)

All schemas identical: True

In [8]:
daily_df.head()

,Unnamed: 0,SOC,SOH,Charging_Cycles,Battery_Temp,Motor_RPM,Motor_Torque,Motor_Temp,Brake_Pad_Wear,Charging_Voltage,Tire_Pressure,DTC
0,2020-01-01 00:00:00,20.0,99.999762,0,27.641960,0.0,0.0,71.031956,100.0,240,34.994742,0
1,2020-01-01 01:00:00,20.0,99.999513,0,31.252744,0.0,0.0,62.665014,100.0,240,34.989558,0
2,2020-01-01 02:00:00,20.0,99.999259,0,33.319184,0.0,0.0,69.339019,100.0,240,34.984385,0
3,2020-01-01 03:00:00,20.0,99.999009,0,30.226656,0.0,0.0,65.951953,100.0,240,34.977987,0
4,2020-01-01 04:00:00,20.0,99.998772,0,32.398368,0.0,0.0,73.412878,100.0,240,34.971496,0

In [9]:
heavy_df.head()

,Unnamed: 0,SOC,SOH,Charging_Cycles,Battery_Temp,Motor_RPM,Motor_Torque,Motor_Temp,Brake_Pad_Wear,Charging_Voltage,Tire_Pressure,DTC
0,2020-01-01 00:00:00,20.0,99.999757,0,31.822998,0.0,0.0,64.937230,100.0,400,34.987175,0
1,2020-01-01 01:00:00,20.0,99.999495,0,31.596741,0.0,0.0,71.637683,100.0,400,34.976006,0
2,2020-01-01 02:00:00,20.0,99.999244,0,31.694791,0.0,0.0,76.626964,100.0,400,34.961510,0
3,2020-01-01 03:00:00,20.0,99.998996,0,29.370583,0.0,0.0,73.446945,100.0,400,34.949125,0
4,2020-01-01 04:00:00,20.0,99.998749,0,30.808790,0.0,0.0,70.240659,100.0,400,34.935932,0

In [10]:
moderate_df.head()

,Unnamed: 0,SOC,SOH,Charging_Cycles,Battery_Temp,Motor_RPM,Motor_Torque,Motor_Temp,Brake_Pad_Wear,Charging_Voltage,Tire_Pressure,DTC
0,2020-01-01 00:00:00,20.0,99.999764,0,31.754530,0.0,0.0,66.097469,100.0,400,34.992077,0
1,2020-01-01 01:00:00,20.0,99.999518,0,30.818005,0.0,0.0,73.668760,100.0,400,34.984849,0
2,2020-01-01 02:00:00,20.0,99.999287,0,29.594818,0.0,0.0,68.756422,100.0,400,34.978068,0
3,2020-01-01 03:00:00,20.0,99.999037,0,29.294351,0.0,0.0,74.696777,100.0,400,34.969152,0
4,2020-01-01 04:00:00,20.0,99.998808,0,27.531188,0.0,0.0,72.709458,100.0,400,34.961127,0

In [11]:
rare_df.head()

,Unnamed: 0,SOC,SOH,Charging_Cycles,Battery_Temp,Motor_RPM,Motor_Torque,Motor_Temp,Brake_Pad_Wear,Charging_Voltage,Tire_Pressure,DTC
0,2020-01-01 00:00:00,20.0,99.999811,0,31.895606,0.0,0.0,64.812536,100.0,240,34.995836,0
1,2020-01-01 01:00:00,20.0,99.999628,0,32.480916,0.0,0.0,71.237563,100.0,240,34.991402,0
2,2020-01-01 02:00:00,20.0,99.999440,0,32.971091,0.0,0.0,71.134825,100.0,240,34.987041,0
3,2020-01-01 03:00:00,20.0,99.999246,0,31.675082,0.0,0.0,72.977871,100.0,240,34.982546,0
4,2020-01-01 04:00:00,20.0,99.999049,0,28.660368,0.0,0.0,71.073983,100.0,240,34.977305,0

In [12]:
daily_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43800 entries, 0 to 43799
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        43800 non-null  str
 1   SOC               43800 non-null  float64
 2   SOH               43800 non-null  float64
 3   Charging_Cycles   43800 non-null  int64
 4   Battery_Temp      43800 non-null  float64
 5   Motor_RPM         43800 non-null  float64
 6   Motor_Torque      43800 non-null  float64
 7   Motor_Temp        43800 non-null  float64
 8   Brake_Pad_Wear    43800 non-null  float64
 9   Charging_Voltage  43800 non-null  int64
 10  Tire_Pressure     43800 non-null  float64
 11  DTC               43800 non-null  str
dtypes: float64(8), int64(2), str(2)
memory usage: 4.8 MB

In [13]:
heavy_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43800 entries, 0 to 43799
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        43800 non-null  str
 1   SOC               43800 non-null  float64
 2   SOH               43800 non-null  float64
 3   Charging_Cycles   43800 non-null  int64
 4   Battery_Temp      43800 non-null  float64
 5   Motor_RPM         43800 non-null  float64
 6   Motor_Torque      43800 non-null  float64
 7   Motor_Temp        43800 non-null  float64
 8   Brake_Pad_Wear    43800 non-null  float64
 9   Charging_Voltage  43800 non-null  int64
 10  Tire_Pressure     43800 non-null  float64
 11  DTC               43800 non-null  str
dtypes: float64(8), int64(2), str(2)
memory usage: 4.8 MB

In [14]:
daily_df["timestamp"] = pd.to_datetime(
    daily_df["Unnamed: 0"],
    errors="coerce"
)

print("Invalid timestamps:", daily_df["timestamp"].isna().sum())

Invalid timestamps: 0

In [15]:
print("Start:", daily_df["timestamp"].min())
print("End:", daily_df["timestamp"].max())

Start: 2020-01-01 00:00:00
End: 2024-12-29 23:00:00

In [16]:
print(
    daily_df["timestamp"]
    .sort_values()
    .diff()
    .value_counts()
    .head(10)
)

timestamp
0 days 01:00:00    43799
Name: count, dtype: int64

In [17]:
print(daily_df[["Unnamed: 0", "timestamp"]].head(10))

            Unnamed: 0           timestamp
0  2020-01-01 00:00:00 2020-01-01 00:00:00
1  2020-01-01 01:00:00 2020-01-01 01:00:00
2  2020-01-01 02:00:00 2020-01-01 02:00:00
3  2020-01-01 03:00:00 2020-01-01 03:00:00
4  2020-01-01 04:00:00 2020-01-01 04:00:00
5  2020-01-01 05:00:00 2020-01-01 05:00:00
6  2020-01-01 06:00:00 2020-01-01 06:00:00
7  2020-01-01 07:00:00 2020-01-01 07:00:00
8  2020-01-01 08:00:00 2020-01-01 08:00:00
9  2020-01-01 09:00:00 2020-01-01 09:00:00